import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React from "react";
import Dropdown from '@/components/Dropdown'
import Table from '@/components/Table'
import CheckboxTwo from '@/components/CheckboxTwo'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [bookData, setData] = React.useState<any[]>([]);

  React.useEffect(() => {
    fetch("http://localhost:3001/api/titles")
    .then((res) => res.json())
  
    .then((data) => {
        setData(bookData => data.book_titles.slice(75,80));
    });
    console.log("BookData in index.tsx", bookData)
}, []);

  return (
    <>
      <Head>
        <title>iBooks to Markdown | By Mortimus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            IBooks to Markdown importer
          </p>
          <div>
            <a
              href="https://mortimus.substack.com"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/mort.png"
                alt="Vercel Logo"
                // className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>
      </main>
      <div className={styles.center}>
          {/* <Dropdown /> */}
          <Table></Table>
      </div>
      
      {/* <div>
        <p className="p-4">This is where the list from the JSON data will arrive:</p>
        <ul>
          {!bookData ? <li>"Loading..."</li> : bookData.map((book, index) => (<li>{book.title}</li>))}
        </ul>
        
      </div> */}
    </>
  )
}
